package com.hyphenate.easeui.model;

import com.hyphenate.easeui.R;
import com.hyphenate.easeui.domain.EaseEmojicon;
import com.hyphenate.easeui.domain.EaseEmojicon.Type;
import com.hyphenate.easeui.utils.EaseSmileUtils;

public class EaseDefaultEmojiconDatas {

    private static String[] emojis = new String[]{
            EaseSmileUtils.ee_00,
            EaseSmileUtils.ee_01,
            EaseSmileUtils.ee_02,
            EaseSmileUtils.ee_03,
            EaseSmileUtils.ee_04,
            EaseSmileUtils.ee_05,
            EaseSmileUtils.ee_06,
            EaseSmileUtils.ee_07,
            EaseSmileUtils.ee_08,
            EaseSmileUtils.ee_09,

            EaseSmileUtils.ee_10,
            EaseSmileUtils.ee_11,
            EaseSmileUtils.ee_12,
            EaseSmileUtils.ee_13,
            EaseSmileUtils.ee_14,
            EaseSmileUtils.ee_15,
            EaseSmileUtils.ee_16,
            EaseSmileUtils.ee_17,
            EaseSmileUtils.ee_18,
            EaseSmileUtils.ee_19,

            EaseSmileUtils.ee_20,
            EaseSmileUtils.ee_21,
            EaseSmileUtils.ee_22,
            EaseSmileUtils.ee_23,
            EaseSmileUtils.ee_24,
            EaseSmileUtils.ee_25,
            EaseSmileUtils.ee_26,
            EaseSmileUtils.ee_27,
            EaseSmileUtils.ee_28,
            EaseSmileUtils.ee_29,

            EaseSmileUtils.ee_30,
            EaseSmileUtils.ee_31,
            EaseSmileUtils.ee_32,
            EaseSmileUtils.ee_33,
            EaseSmileUtils.ee_34,
            EaseSmileUtils.ee_35,
            EaseSmileUtils.ee_36,
            EaseSmileUtils.ee_37,
            EaseSmileUtils.ee_38,
            EaseSmileUtils.ee_39,

            EaseSmileUtils.ee_40,
            EaseSmileUtils.ee_41,
            EaseSmileUtils.ee_42,
            EaseSmileUtils.ee_43,
            EaseSmileUtils.ee_44,
            EaseSmileUtils.ee_45,
            EaseSmileUtils.ee_46,
            EaseSmileUtils.ee_47,
            EaseSmileUtils.ee_48,
            EaseSmileUtils.ee_49,

            EaseSmileUtils.ee_50,
            EaseSmileUtils.ee_51,
            EaseSmileUtils.ee_52,
            EaseSmileUtils.ee_53,
            EaseSmileUtils.ee_54,
            EaseSmileUtils.ee_55,
            EaseSmileUtils.ee_56,
            EaseSmileUtils.ee_57,
            EaseSmileUtils.ee_58,
            EaseSmileUtils.ee_59,

            EaseSmileUtils.ee_60,
            EaseSmileUtils.ee_61,
            EaseSmileUtils.ee_62,
            EaseSmileUtils.ee_63,
            EaseSmileUtils.ee_64,
            EaseSmileUtils.ee_65,
            EaseSmileUtils.ee_66,
            EaseSmileUtils.ee_67,
            EaseSmileUtils.ee_68,
            EaseSmileUtils.ee_69,

            EaseSmileUtils.ee_70,
            EaseSmileUtils.ee_71,
            EaseSmileUtils.ee_72,
            EaseSmileUtils.ee_73,
            EaseSmileUtils.ee_74,
            EaseSmileUtils.ee_75,
            EaseSmileUtils.ee_76,
            EaseSmileUtils.ee_77,
            EaseSmileUtils.ee_78,
            EaseSmileUtils.ee_79,

            EaseSmileUtils.ee_80,
            EaseSmileUtils.ee_81,
            EaseSmileUtils.ee_82,
            EaseSmileUtils.ee_83,
            EaseSmileUtils.ee_84,
            EaseSmileUtils.ee_85,
            EaseSmileUtils.ee_86,
            EaseSmileUtils.ee_87,
            EaseSmileUtils.ee_88,
            EaseSmileUtils.ee_89,

            EaseSmileUtils.ee_90,
            EaseSmileUtils.ee_91,
            EaseSmileUtils.ee_92,
            EaseSmileUtils.ee_93,
            EaseSmileUtils.ee_94,
            EaseSmileUtils.ee_95,
            EaseSmileUtils.ee_96,
            EaseSmileUtils.ee_97,
            EaseSmileUtils.ee_98,
            EaseSmileUtils.ee_99,

            EaseSmileUtils.ee_100,
            EaseSmileUtils.ee_101,
            EaseSmileUtils.ee_102,
            EaseSmileUtils.ee_103,
            EaseSmileUtils.ee_104,
            EaseSmileUtils.ee_105,
            EaseSmileUtils.ee_106,
            EaseSmileUtils.ee_107,
            EaseSmileUtils.ee_108,
            EaseSmileUtils.ee_109,

            EaseSmileUtils.ee_110,
            EaseSmileUtils.ee_111,
            EaseSmileUtils.ee_112,
            EaseSmileUtils.ee_113,
            EaseSmileUtils.ee_114,
            EaseSmileUtils.ee_115,
            EaseSmileUtils.ee_160,
            EaseSmileUtils.ee_161,
            EaseSmileUtils.ee_162,
            EaseSmileUtils.ee_163,

            EaseSmileUtils.ee_164,
            EaseSmileUtils.ee_165,
            EaseSmileUtils.ee_166,
            EaseSmileUtils.ee_167,

    };

    private static int[] icons = new int[]{
            R.drawable.emoji_00,
            R.drawable.emoji_01,
            R.drawable.emoji_02,
            R.drawable.emoji_03,
            R.drawable.emoji_04,
            R.drawable.emoji_05,
            R.drawable.emoji_06,
            R.drawable.emoji_07,
            R.drawable.emoji_08,
            R.drawable.emoji_09,

            R.drawable.emoji_10,
            R.drawable.emoji_11,
            R.drawable.emoji_12,
            R.drawable.emoji_13,
            R.drawable.emoji_14,
            R.drawable.emoji_15,
            R.drawable.emoji_16,
            R.drawable.emoji_17,
            R.drawable.emoji_18,
            R.drawable.emoji_19,

            R.drawable.emoji_20,
            R.drawable.emoji_21,
            R.drawable.emoji_22,
            R.drawable.emoji_23,
            R.drawable.emoji_24,
            R.drawable.emoji_25,
            R.drawable.emoji_26,
            R.drawable.emoji_27,
            R.drawable.emoji_28,
            R.drawable.emoji_29,

            R.drawable.emoji_30,
            R.drawable.emoji_31,
            R.drawable.emoji_32,
            R.drawable.emoji_33,
            R.drawable.emoji_34,
            R.drawable.emoji_35,
            R.drawable.emoji_36,
            R.drawable.emoji_37,
            R.drawable.emoji_38,
            R.drawable.emoji_39,

            R.drawable.emoji_40,
            R.drawable.emoji_41,
            R.drawable.emoji_42,
            R.drawable.emoji_43,
            R.drawable.emoji_44,
            R.drawable.emoji_45,
            R.drawable.emoji_46,
            R.drawable.emoji_47,
            R.drawable.emoji_48,
            R.drawable.emoji_49,

            R.drawable.emoji_50,
            R.drawable.emoji_51,
            R.drawable.emoji_52,
            R.drawable.emoji_53,
            R.drawable.emoji_54,
            R.drawable.emoji_55,
            R.drawable.emoji_56,
            R.drawable.emoji_57,
            R.drawable.emoji_58,
            R.drawable.emoji_59,

            R.drawable.emoji_60,
            R.drawable.emoji_61,
            R.drawable.emoji_62,
            R.drawable.emoji_63,
            R.drawable.emoji_64,
            R.drawable.emoji_65,
            R.drawable.emoji_66,
            R.drawable.emoji_67,
            R.drawable.emoji_68,
            R.drawable.emoji_69,

            R.drawable.emoji_70,
            R.drawable.emoji_71,
            R.drawable.emoji_72,
            R.drawable.emoji_73,
            R.drawable.emoji_74,
            R.drawable.emoji_75,
            R.drawable.emoji_76,
            R.drawable.emoji_77,
            R.drawable.emoji_78,
            R.drawable.emoji_79,

            R.drawable.emoji_80,
            R.drawable.emoji_81,
            R.drawable.emoji_82,
            R.drawable.emoji_83,
            R.drawable.emoji_84,
            R.drawable.emoji_85,
            R.drawable.emoji_86,
            R.drawable.emoji_87,
            R.drawable.emoji_88,
            R.drawable.emoji_89,

            R.drawable.emoji_90,
            R.drawable.emoji_91,
            R.drawable.emoji_92,
            R.drawable.emoji_93,
            R.drawable.emoji_94,
            R.drawable.emoji_95,
            R.drawable.emoji_96,
            R.drawable.emoji_97,
            R.drawable.emoji_98,
            R.drawable.emoji_99,

            R.drawable.emoji_100,
            R.drawable.emoji_101,
            R.drawable.emoji_102,
            R.drawable.emoji_103,
            R.drawable.emoji_104,
            R.drawable.emoji_105,
            R.drawable.emoji_106,
            R.drawable.emoji_107,
            R.drawable.emoji_108,
            R.drawable.emoji_109,

            R.drawable.emoji_110,
            R.drawable.emoji_111,
            R.drawable.emoji_112,
            R.drawable.emoji_113,
            R.drawable.emoji_114,
            R.drawable.emoji_115,

            R.drawable.emoji_160,
            R.drawable.emoji_161,
            R.drawable.emoji_162,
            R.drawable.emoji_163,
            R.drawable.emoji_164,
            R.drawable.emoji_165,
            R.drawable.emoji_166,
            R.drawable.emoji_167,
    };


    private static final EaseEmojicon[] DATA = createData();

    private static EaseEmojicon[] createData() {
        EaseEmojicon[] datas = new EaseEmojicon[icons.length];
        for (int i = 0; i < icons.length; i++) {
            datas[i] = new EaseEmojicon(icons[i], emojis[i], Type.NORMAL);
        }
        return datas;
    }

    public static EaseEmojicon[] getData() {
        return DATA;
    }
}
